# Generated by Django 5.2.4 on 2025-08-05 07:11

import django.db.models.deletion
import django_mongodb_backend.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DecimalFieldModel",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FooModel",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("json_field", models.JSONField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "name2",
                    models.CharField(db_column="name_2", max_length=100, null=True),
                ),
                ("int_field", models.IntegerField(default=0)),
                ("datetime_field", models.DateTimeField(auto_now_add=True)),
                ("time_field", models.TimeField(auto_now_add=True)),
                ("date_field", models.DateField(auto_now_add=True)),
                (
                    "nested_field",
                    models.CharField(db_column="nested.field", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DifferentTableOneToOne",
            fields=[
                (
                    "dummy_model",
                    models.OneToOneField(
                        db_column="_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="another_extends",
                        serialize=False,
                        to="testapp.foomodel",
                    ),
                ),
                ("extra", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SameTableChild",
            fields=[
                (
                    "dummy_model_ptr",
                    models.OneToOneField(
                        db_column="_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="child_type",
                        serialize=False,
                        to="testapp.foomodel",
                    ),
                ),
                ("extended", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "testapp_foomodel",
            },
            bases=("testapp.foomodel",),
        ),
        migrations.CreateModel(
            name="SameTableOneToOne",
            fields=[
                (
                    "dummy_model",
                    models.OneToOneField(
                        db_column="_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="extends",
                        serialize=False,
                        to="testapp.foomodel",
                    ),
                ),
                ("extra", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "testapp_foomodel",
            },
        ),
        migrations.CreateModel(
            name="RelatedModel",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "foo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related",
                        to="testapp.foomodel",
                    ),
                ),
            ],
        ),
    ]
