# Generated by Django 5.0.1 on 2024-01-10 21:14

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmodel",
            name="json_field",
            field=django_jsonform.models.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testmodel",
            name="name",
            field=models.CharField(default="bar", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testmodel",
            name="name2",
            field=models.CharField(default="bar", max_length=100),
            preserve_default=False,
        ),
    ]
