# Generated by Django 5.0.1 on 2024-01-10 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_testmodel_json_field_testmodel_name_testmodel_name2"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TestModel",
            new_name="DummyModel",
        ),
    ]
