# Generated by Django 4.2.9 on 2024-01-11 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_rename_testmodel_dummymodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dummymodel",
            name="json_field",
        ),
        migrations.RemoveField(
            model_name="dummymodel",
            name="name2",
        ),
    ]
