# Generated by Django 4.2.9 on 2024-01-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("refapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refmodel",
            name="json",
            field=models.JSONField(default=dict),
        ),
    ]
